# Copy the built sound pack and the sfx library into the deployed mod folder.
#
# Scoped to sounds\ and one named ini ON PURPOSE. Everything else under
# papyrus\mods\Physical Ragdoll Sounds\ is hand-maintained - meta.ini, the working
# ini, the pristine pair under deployment_files - and a broader copy would quietly
# overwrite it. assets\sfx\ is wholly generated by tools\sfx.py, so it is the one
# directory where the repo is the source of truth rather than the deployed folder;
# RagdollSounds_SFX.ini is named file by file for the same reason.
#
# Three things are copied, and they are different in kind.
#
#   assets\sfx\*.wav          -> sounds\
#       The built pack. Named `<slot>_<NN>.wav`, and the fallback for any slot
#       RagdollSounds_SFX.ini has nothing to say about.
#   assets\sfx\library\*      -> sounds\library\
#       Everything the testbench has imported, with its `.meta.ini` sidecars.
#       This is what the ini's assignments name, so the two travel together: an
#       ini naming a file the install does not have is a slot playing one fewer
#       variant than it says, and the log is the only place that shows up.
#
#   deployment_files\main\...\RagdollSounds_SFX.ini -> SKSE\Plugins\RagdollSounds\
#       The assignments themselves. The testbench writes them into
#       deployment_files\ because that is the release overlay, and for a long
#       time that was the end of it - which meant the ini reached people who
#       downloaded the mod and never reached the machine it was written on. An
#       unlinked game read no assignments at all and every slot fell back to the
#       filename convention, so scrape_limb was a procedural stand-in while the
#       testbench beside it was playing a recording.
#
# The third copy is the one with a trap in it, and `-Mo2Overwrite` is that trap:
# the plugin round-trips its inis at startup, and a write through MO2's VFS lands
# in `overwrite\` rather than in the mod. That copy then *shadows* the mod's own
# for every later launch, so deploying an ini into the mod folder alone changes
# nothing at all. The stale one is removed here, and the next launch writes a
# fresh one from what it read - which is now this file.
#
# Run after `sfx.py make` has changed the pack, or after importing into the
# library. build-skse-mods.ps1 deploys the DLL and nothing else, which is why
# this exists separately.
#
#   pwsh -File deploy-pack.ps1 [-WhatIf]

[CmdletBinding(SupportsShouldProcess)]
param(
    # MO2's overwrite folder for the instance that gets played. Empty to leave it
    # alone entirely - on a machine with no MO2 there is nothing to shadow, and
    # the deploy is just the two copies above.
    [string] $Mo2Overwrite = 'C:\games\skyrim\MGON\overwrite'
)

$ErrorActionPreference = 'Stop'

$source = Join-Path $PSScriptRoot 'assets\sfx'
$dest = Join-Path $PSScriptRoot '..\..\papyrus\mods\Physical Ragdoll Sounds\SKSE\Plugins\RagdollSounds\sounds'

if (-not (Test-Path $source)) {
    throw "no pack at $source - has sfx.py been run?"
}

if (-not (Test-Path $dest)) {
    $null = New-Item -ItemType Directory -Path $dest -Force
}
$dest = (Resolve-Path $dest).Path

$wavs = Get-ChildItem -Path $source -Filter '*.wav' -File
if ($wavs.Count -eq 0) {
    throw "no wavs under $source"
}

# Stale files are removed rather than left: a slot's variants are indexed by their
# position in the sorted set, so a file the pack no longer contains does not just
# sit there unused - it shifts every variant after it and a cue plays a different
# sound than the one the engine chose.
$keep = $wavs.Name
Get-ChildItem -Path $dest -Filter '*.wav' -File |
    Where-Object { $keep -notcontains $_.Name } |
    ForEach-Object {
        if ($PSCmdlet.ShouldProcess($_.FullName, 'remove stale pack file')) {
            Remove-Item $_.FullName -Force
        }
        Write-Host "  - $($_.Name)" -ForegroundColor DarkYellow
    }

$copied = 0
foreach ($wav in $wavs) {
    $target = Join-Path $dest $wav.Name
    $same = (Test-Path $target) -and
            ((Get-FileHash $wav.FullName -Algorithm SHA256).Hash -eq
             (Get-FileHash $target -Algorithm SHA256).Hash)
    if ($same) { continue }
    if ($PSCmdlet.ShouldProcess($target, 'copy')) {
        Copy-Item $wav.FullName $target -Force
    }
    Write-Host "  + $($wav.Name)" -ForegroundColor DarkGreen
    $copied++
}

Write-Host "pack: $($wavs.Count) file(s), $copied changed -> $dest" -ForegroundColor Green

# ── the library ──────────────────────────────────────────────────────────────
#
# Mirrored rather than merged: a file the repo's library no longer holds is one
# the ini cannot be naming any more, and leaving it behind only grows the
# install. Sidecars come along - they are what the testbench reads back on the
# next run, and on a machine that only ever runs the game they cost a few
# kilobytes and explain what every file is.

$libSource = Join-Path $PSScriptRoot 'assets\sfx\library'
# Under sounds\, not beside it: plugin.cpp reads
# Data/SKSE/Plugins/RagdollSounds/sounds/library, and a library one directory up
# is 788 files the game never opens.
$libDest = Join-Path $dest 'library'

if (Test-Path $libSource) {
    if (-not (Test-Path $libDest)) {
        $null = New-Item -ItemType Directory -Path $libDest -Force
    }
    $libDest = (Resolve-Path $libDest).Path

    $libFiles = Get-ChildItem -Path $libSource -File
    $libKeep = $libFiles.Name
    Get-ChildItem -Path $libDest -File |
        Where-Object { $libKeep -notcontains $_.Name } |
        ForEach-Object {
            if ($PSCmdlet.ShouldProcess($_.FullName, 'remove stale library file')) {
                Remove-Item $_.FullName -Force
            }
            Write-Host "  - library\$($_.Name)" -ForegroundColor DarkYellow
        }

    $libCopied = 0
    foreach ($file in $libFiles) {
        $target = Join-Path $libDest $file.Name
        $same = (Test-Path $target) -and
                ((Get-FileHash $file.FullName -Algorithm SHA256).Hash -eq
                 (Get-FileHash $target -Algorithm SHA256).Hash)
        if ($same) { continue }
        if ($PSCmdlet.ShouldProcess($target, 'copy')) {
            Copy-Item $file.FullName $target -Force
        }
        Write-Host "  + library\$($file.Name)" -ForegroundColor DarkGreen
        $libCopied++
    }

    Write-Host "library: $($libFiles.Count) file(s), $libCopied changed -> $libDest" -ForegroundColor Green
} else {
    Write-Host "library: nothing at $libSource - the ini's assignments will all fall back" -ForegroundColor DarkGray
}

# ── the assignments ──────────────────────────────────────────────────────────
#
# Beside the library on purpose: an ini naming files the install does not have is
# the one failure the log alone explains, so the two are deployed in one pass or
# not at all.

$sfxIni = Join-Path $PSScriptRoot '..\..\papyrus\mods\Physical Ragdoll Sounds\deployment_files\main\SKSE\Plugins\RagdollSounds\RagdollSounds_SFX.ini'
if (Test-Path $sfxIni) {
    $sfxIni = (Resolve-Path $sfxIni).Path
    # Beside the pack rather than inside it: plugin.cpp reads the three inis from
    # Data/SKSE/Plugins/RagdollSounds, one directory up from sounds\.
    $sfxDest = Join-Path (Split-Path $dest -Parent) 'RagdollSounds_SFX.ini'

    $same = (Test-Path $sfxDest) -and
            ((Get-FileHash $sfxIni -Algorithm SHA256).Hash -eq
             (Get-FileHash $sfxDest -Algorithm SHA256).Hash)
    if ($same) {
        Write-Host "assignments: unchanged -> $sfxDest" -ForegroundColor Green
    } else {
        if ($PSCmdlet.ShouldProcess($sfxDest, 'copy')) {
            Copy-Item $sfxIni $sfxDest -Force
        }
        $slots = @(Select-String -Path $sfxIni -Pattern '^Sfx = .' ).Count
        Write-Host "assignments: $slots slot(s) -> $sfxDest" -ForegroundColor Green
    }

    # The shadow. See the header: while this exists the game reads it and not the
    # copy above, and the one sitting there now is the empty template the plugin
    # generated on a launch that had no ini to read.
    if ($Mo2Overwrite) {
        $shadow = Join-Path $Mo2Overwrite 'SKSE\Plugins\RagdollSounds\RagdollSounds_SFX.ini'
        if (Test-Path $shadow) {
            $shadowSlots = @(Select-String -Path $shadow -Pattern '^Sfx = .').Count
            $deployedSlots = @(Select-String -Path $sfxIni -Pattern '^Sfx = .').Count
            if ($shadowSlots -gt $deployedSlots) {
                # Somebody assigned slots in-game and this is the only copy of it.
                # Removing it would be deleting the newer file to install the
                # older one, which is not a deploy.
                Write-Host "overwrite: $shadow has $shadowSlots assignment(s) against $deployedSlots here - left alone, and it is what the game will read" -ForegroundColor Yellow
            } else {
                if ($PSCmdlet.ShouldProcess($shadow, 'remove shadowing ini')) {
                    Remove-Item $shadow -Force
                }
                Write-Host "overwrite: removed $shadow ($shadowSlots assignment(s)) - it was shadowing the mod's copy" -ForegroundColor DarkYellow
            }
        }
    }
} else {
    Write-Host "assignments: no RagdollSounds_SFX.ini yet - every slot falls back to <slot>_NN.wav" -ForegroundColor DarkGray
}
