# Copy the built sound pack and the sfx library into the deployed mod folder.
#
# Scoped to sounds\ ON PURPOSE. Everything else under papyrus\mods\Physical Ragdoll
# Sounds\ is hand-maintained - meta.ini, the working ini, the pristine pair under
# deployment_files - and a broader copy would quietly overwrite it. assets\sfx\ is
# wholly generated by tools\sfx.py, so it is the one directory where the repo is
# the source of truth rather than the deployed folder.
#
# Two things are copied, and they are different in kind.
#
#   assets\sfx\*.wav          -> sounds\
#       The built pack. Named `<slot>_<NN>.wav`, and the fallback for any slot
#       RagdollSounds_SFX.ini has nothing to say about.
#   assets\sfx\library\*      -> sounds\library\
#       Everything the testbench has imported, with its `.meta.ini` sidecars.
#       This is what the ini's assignments name, so the two travel together: an
#       ini naming a file the install does not have is a slot playing one fewer
#       variant than it says, and the log is the only place that shows up.
#
# The ini itself is NOT copied - the testbench writes it straight into
# deployment_files\, so it is already where it belongs and copying it here
# would fight whoever last saved.
#
# Run after `sfx.py make` has changed the pack, or after importing into the
# library. build-skse-mods.ps1 deploys the DLL and nothing else, which is why
# this exists separately.
#
#   pwsh -File deploy-pack.ps1 [-WhatIf]

[CmdletBinding(SupportsShouldProcess)]
param()

$ErrorActionPreference = 'Stop'

$source = Join-Path $PSScriptRoot 'assets\sfx'
$dest = Join-Path $PSScriptRoot '..\..\papyrus\mods\Physical Ragdoll Sounds\SKSE\Plugins\RagdollSounds\sounds'

if (-not (Test-Path $source)) {
    throw "no pack at $source - has sfx.py been run?"
}

if (-not (Test-Path $dest)) {
    $null = New-Item -ItemType Directory -Path $dest -Force
}
$dest = (Resolve-Path $dest).Path

$wavs = Get-ChildItem -Path $source -Filter '*.wav' -File
if ($wavs.Count -eq 0) {
    throw "no wavs under $source"
}

# Stale files are removed rather than left: a slot's variants are indexed by their
# position in the sorted set, so a file the pack no longer contains does not just
# sit there unused - it shifts every variant after it and a cue plays a different
# sound than the one the engine chose.
$keep = $wavs.Name
Get-ChildItem -Path $dest -Filter '*.wav' -File |
    Where-Object { $keep -notcontains $_.Name } |
    ForEach-Object {
        if ($PSCmdlet.ShouldProcess($_.FullName, 'remove stale pack file')) {
            Remove-Item $_.FullName -Force
        }
        Write-Host "  - $($_.Name)" -ForegroundColor DarkYellow
    }

$copied = 0
foreach ($wav in $wavs) {
    $target = Join-Path $dest $wav.Name
    $same = (Test-Path $target) -and
            ((Get-FileHash $wav.FullName -Algorithm SHA256).Hash -eq
             (Get-FileHash $target -Algorithm SHA256).Hash)
    if ($same) { continue }
    if ($PSCmdlet.ShouldProcess($target, 'copy')) {
        Copy-Item $wav.FullName $target -Force
    }
    Write-Host "  + $($wav.Name)" -ForegroundColor DarkGreen
    $copied++
}

Write-Host "pack: $($wavs.Count) file(s), $copied changed -> $dest" -ForegroundColor Green

# ── the library ──────────────────────────────────────────────────────────────
#
# Mirrored rather than merged: a file the repo's library no longer holds is one
# the ini cannot be naming any more, and leaving it behind only grows the
# install. Sidecars come along - they are what the testbench reads back on the
# next run, and on a machine that only ever runs the game they cost a few
# kilobytes and explain what every file is.

$libSource = Join-Path $PSScriptRoot 'assets\sfx\library'
$libDest = Join-Path (Split-Path $dest -Parent) 'library'

if (Test-Path $libSource) {
    if (-not (Test-Path $libDest)) {
        $null = New-Item -ItemType Directory -Path $libDest -Force
    }
    $libDest = (Resolve-Path $libDest).Path

    $libFiles = Get-ChildItem -Path $libSource -File
    $libKeep = $libFiles.Name
    Get-ChildItem -Path $libDest -File |
        Where-Object { $libKeep -notcontains $_.Name } |
        ForEach-Object {
            if ($PSCmdlet.ShouldProcess($_.FullName, 'remove stale library file')) {
                Remove-Item $_.FullName -Force
            }
            Write-Host "  - library\$($_.Name)" -ForegroundColor DarkYellow
        }

    $libCopied = 0
    foreach ($file in $libFiles) {
        $target = Join-Path $libDest $file.Name
        $same = (Test-Path $target) -and
                ((Get-FileHash $file.FullName -Algorithm SHA256).Hash -eq
                 (Get-FileHash $target -Algorithm SHA256).Hash)
        if ($same) { continue }
        if ($PSCmdlet.ShouldProcess($target, 'copy')) {
            Copy-Item $file.FullName $target -Force
        }
        Write-Host "  + library\$($file.Name)" -ForegroundColor DarkGreen
        $libCopied++
    }

    Write-Host "library: $($libFiles.Count) file(s), $libCopied changed -> $libDest" -ForegroundColor Green
} else {
    Write-Host "library: nothing at $libSource - the ini's assignments will all fall back" -ForegroundColor DarkGray
}

# The assignment ini, only to say whether it exists. It is written straight into
# deployment_files\ by the testbench; if it is missing, every slot falls back to
# the filename convention and the mod sounds exactly as it did before this
# existed - which is a fine state to be in, but worth knowing you are in.
$sfxIni = Join-Path $PSScriptRoot '..\..\papyrus\mods\Physical Ragdoll Sounds\deployment_files\main\SKSE\Plugins\RagdollSounds\RagdollSounds_SFX.ini'
if (Test-Path $sfxIni) {
    Write-Host "assignments: $((Resolve-Path $sfxIni).Path)" -ForegroundColor Green
} else {
    Write-Host "assignments: no RagdollSounds_SFX.ini yet - every slot falls back to <slot>_NN.wav" -ForegroundColor DarkGray
}
